#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

set_time_limit(600);

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Application('Doggo');

$app->add(new TwentyOneSix\Doggo\Installer\WordPress);

$app->run();
