#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Doggo');

$app->add(new TwentyOneSix\Doggo\Installer\WordPress);

$app->run();
