#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Ordú');

$app->add(new TwentyOneSix\Ordu\Installer\WordPress);

$app->run();
